### PR TITLE
align the name part of struct spiffs_page_object_ix_header

### PR DESCRIPTION
**Pull request by nodemcu**
un-aligned file name in flash may cause problem in esp8266.

### CODE REVIEW

**Comment by nodemcu** [comment]
esp8266 read spi flash api will reboot mcu when it's read from a not-4-bytes-aligned flash address.
when in nodemcu:
```lua
file.open("name","w")
file.write("--")
file.close()  --this line cause reboot
```
maybe it's only the feature of esp8266(xtensa arch).

**Comment by pellepl** [comment]
That's weird. Could you please try this - keep the alignment addition you
have (when it works), but change the length of filename from 16 to 17.

I suspect it is actually not the name pointer that is important but the
data that comes afterwards. Then the real fix would be to align the whole
struct instead.

Thanks / Peter

2015-03-19 11:38 GMT+01:00 zeroday <notifications@github.com>:

**Comment by nodemcu** [comment]
yes, I am changing file name from 32 to 33. and it fails.
the alignment kept, so it's not the name but the whole structure.
and if I align the whole struct, it works.

**Comment by pellepl** [comment]
Ok good. I'll add support for this in spiffs_config.h in a not-so-far future. Thanks for testing.

**Comment by nodemcu** [comment]
thanks
I will align the struct for a quick fix and wait for the update.

**Comment by pellepl** [comment]
Updated. See changelog in reade.md. Cheers

**Comment by nodemcu** [comment]
Great, thank you~

**Pull request closed without merging**
